In [63]:
import pandas as pd

In [64]:
df = pd.read_csv('B2W-Reviews01.csv')

/var/folders/vb/q6czv8r938d0bnqp76zgy5km0000gn/T/ipykernel_35810/1153590322.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('B2W-Reviews01.csv')


In [65]:
texts = df['review_text']

In [66]:
texts = texts.dropna()

In [67]:
texts = texts.reset_index(drop=True)

In [68]:
texts

0         Estou contente com a compra entrega rápida o ú...
1         Por apenas R$1994.20,eu consegui comprar esse ...
2         SUPERA EM AGILIDADE E PRATICIDADE OUTRAS PANEL...
3         MEU FILHO AMOU! PARECE DE VERDADE COM TANTOS D...
4         A entrega foi no prazo, as americanas estão de...
                                ...                        
129093    Vale muito, estou usando no controle do Xbox e...
129094    Prático e barato, super indico o produto para ...
129095    Chegou antes do prazo previsto e corresponde a...
129096    Material fraco, poderia ser melhor. Ficou deve...
129097    Comprei esse produto, quando chegou estava com...
Name: review_text, Length: 129098, dtype: object

In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(texts)

In [70]:
tfidf.toarray().shape

(129098, 50336)

In [71]:
tfidf_array = tfidf.toarray()[:10000]

In [98]:
input_review = 'a bateria do produto explodiu e pegou fogo'

In [99]:
input_vec = tfidf_vectorizer.transform([input_review])

In [100]:
input_vec.toarray().shape

(1, 50336)

In [101]:
input_array = input_vec.toarray()

In [102]:
input_array[input_array != 0]

array([0.29367434, 0.14407234, 0.58662715, 0.51729893, 0.51886063,
       0.10978431])

In [103]:
from sklearn.metrics.pairwise import cosine_similarity

In [104]:
similarities = cosine_similarity(input_array, tfidf_array)

In [105]:
similarities

array([[0.02260786, 0.        , 0.        , ..., 0.        , 0.00857782,
        0.01188774]])

In [106]:
import numpy as np

In [107]:
similarities_index = np.argsort(similarities)[0]

In [108]:
top_10 = similarities_index[:-11:-1]
top_10

array([4601, 7935, 8475, 2424, 4512, 5817, 6253, 8546, 6176, 2994])

In [109]:
for index in top_10:
    print(texts[index] + '\n')

O produto não é original explodiu e queimou parte da minha casa, irei processar a americanas.

achei péssimo ,a agua vaza sem parar molhando tudo,não mantém a temperatura,a tomada superaqueceu e derreteu por pouco não pegou fogo ,usei duas vezes,desisti vou comprar outro de outra marca ,esse nunca mais.

Comprei o produto para presentear minha esposa , estamos viajando e ela usou uma vez e o produto esquenta e fica com a parte traseira encandecente como se fosse pegar fogo, ou seja vou pedir q troca assim que retornar da viagem. A chapinha não teve problema mais o secador não funciona e com medo de queimar ou pegar fogo e derreter preferimos não usar .

Aparelho muito bom. Wi fi pegou facil e estável. Bom para séries e filmes. Tem bom acabamento e funcionalidade.

Muito bom o produto, só a bateria q não é muito boa.

Excelente produto, supriu a minha necessidade! O único ponto do qual me pegou de surpresa é que só funciona através do controle remoto, não vem interruptor! Mas isso não i